item {
  id: 1
  name: 'Pachypodium brevicaule'
}

item {
  id: 2
  name: 'Pachypodium geayi'
}

item {
  id: 3
  name: 'Pachypodium lamerei Drake'
}

item {
  id: 4
  name: 'Pachypodium meridionale'
}

item {
  id: 5
  name: 'Pachypodium rosulatum'
}

item {
  id: 6
  name: 'Pachypodium saundersii'
}